name: Build and Push Docker image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check commit message
        id: check_commit
        run: |
          echo "commit_message=${{ github.event.head_commit.message }}" >> $GITHUB_OUTPUT

      - name: Exit if commit message doesn't contain redeploy key
        if: ${{ !contains(steps.check_commit.outputs.commit_message, 'THN-znUa@<Gb2F8,j}m]') }}
        run: |
          echo "Commit message doesn't contain redeploy key. Skipping deployment."
          exit 1

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/html-server:latest .

      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/html-server:latest
